//
//  TarotAssets.swift
//  tarot-ar
//
//  Created by Issarapong Poesua on 22/10/21.
//

enum TarotAssets: String, CaseIterable {
    
    case theFool            = "00-TheFool"
    case theMagician        = "01-TheMagician"
    case theHighPriestess   = "02-TheHighPriestess"
    case theEmpress         = "03-TheEmpress"
    case theEmperor         = "04-TheEmperor"
    case theHierophant      = "05-TheHierophant"
    case theLovers          = "06-TheLovers"
    case theChariot         = "07-TheChariot"
    case strength           = "08-Strength"
    case theHermit          = "09-TheHermit"
    case whellOfFortune     = "10-WheelOfFortune"
    case justice            = "11-Justice"
    case theHangedMan       = "12-TheHangedMan"
    case death              = "13-Death"
    case temperance         = "14-Temperance"
    case theDevil           = "15-TheDevil"
    case theTower           = "16-TheTower"
    case theStar            = "17-TheStar"
    case theMoon            = "18-TheMoon"
    case theSun             = "19-TheSun"
    case judgement          = "20-Judgement"
    case theWorld           = "21-TheWorld"
    
    case cups01              = "Cups01"
    case cups02              = "Cups02"
    case cups03              = "Cups03"
    case cups04              = "Cups04"
    case cups05              = "Cups05"
    case cups06              = "Cups06"
    case cups07              = "Cups07"
    case cups08              = "Cups08"
    case cups09              = "Cups09"
    case cups10              = "Cups10"
    case cups11              = "Cups11"
    case cups12              = "Cups12"
    case cups13              = "Cups13"
    case cups14              = "Cups14"
    
    case pentacles01        = "Pentacles01"
    case pentacles02        = "Pentacles02"
    case pentacles03        = "Pentacles03"
    case pentacles04        = "Pentacles04"
    case pentacles05        = "Pentacles05"
    case pentacles06        = "Pentacles06"
    case pentacles07        = "Pentacles07"
    case pentacles08        = "Pentacles08"
    case pentacles09        = "Pentacles09"
    case pentacles10        = "Pentacles10"
    case pentacles11        = "Pentacles11"
    case pentacles12        = "Pentacles12"
    case pentacles13        = "Pentacles13"
    case pentacles14        = "Pentacles14"
    
    case swords01           = "Swords01"
    case swords02           = "Swords02"
    case swords03           = "Swords03"
    case swords04           = "Swords04"
    case swords05           = "Swords05"
    case swords06           = "Swords06"
    case swords07           = "Swords07"
    case swords08           = "Swords08"
    case swords09           = "Swords09"
    case swords10           = "Swords10"
    case swords11           = "Swords11"
    case swords12           = "Swords12"
    case swords13           = "Swords13"
    case swords14           = "Swords14"
    
    case wans01             = "Wands01"
    case wans02             = "Wands02"
    case wans03             = "Wands03"
    case wans04             = "Wands04"
    case wans05             = "Wands05"
    case wans06             = "Wands06"
    case wans07             = "Wands07"
    case wans08             = "Wands08"
    case wans09             = "Wands09"
    case wans10             = "Wands10"
    case wans11             = "Wands11"
    case wans12             = "Wands12"
    case wans13             = "Wands13"
    case wans14             = "Wands14"

}
